Feat/prsd 637 look for property registration in database
communitiesuk/prsdb-webapp pull request #102
Opened 2024-12-11 22:19 UTC by JasminConterioSW

- Add database entities / repositories for:
    - Property
    - PropertyOwnership
    - Payment (this one is linked to PropertyOwnership)
- Add PropertyRegistrationService with a function to check if the address is registered, along with tests.
- Use the service to check the database in addressAlreadyRegistered in the PropertyRegistrationJourney.

FYI an address is considered registered if 
- The property with that address which is active and
- There is a current and active property ownership for the active property

2024-12-12 11:52 UTC, AEPR requested changes
Some thoughts, mostly, on relationship numbering and constraints. Overall looking good though.

2024-12-12 11:52 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/PropertyOwnership.kt
> +        private set
Actually, having read the tests - I think this needs to be ManyToOne as well, because we can have several inactive ownerships for a property, but only one active one. I've had a look and I think there's something we can add to the migration to sort this out though. (I'll comment there)

2024-12-12 11:52 UTC, AEPR commented on src/main/resources/db/migrations/V1_8_0__property_ownership_tables.sql
> +    ADD CONSTRAINT uc_propertyownership_property UNIQUE (property_id);
As noted elsewhere, we need to allow multiple `property_ownership`s per `property`, but only want to allow one to be active. We can acheive this by adding a "partial index"([see docs](https://www.postgresql.org/docs/current/indexes-partial.html#INDEXES-PARTIAL-EX3)) like this:
```
CREATE UNIQUE INDEX one_active_ownership_per_property ON property_ownership(property_id)
    WHERE is_active;
```

I'm not sure what performance impacts this will have, but making the database enforce this rule seems likely worth it to me.

2024-12-12 12:53 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/Payment.kt
> +        private set
Is there a way of enforcing a 'one to at least one' relationship here?

2024-12-12 12:53 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/Property.kt
> +    var hasGasSupply: Boolean? = null
These should be set to non-nullable as well

2024-12-12 12:53 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/PropertyOwnership.kt
> +        private set
These (except `tenancyStartDate`) need to be non-nullable

2024-12-12 12:53 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/PropertyOwnership.kt
> +    @JoinColumn(name = "payment_id", nullable = false)
I think the foreign key name should be set here, to match our convention

2024-12-12 12:53 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyRegistrationService.kt
> +@Scope(value = WebApplicationContext.SCOPE_REQUEST, proxyMode = ScopedProxyMode.TARGET_CLASS)
I don't think scope is needed here at all, since this service isn't interacting with session data

2024-12-12 12:53 UTC, isobel-softwire commented on src/main/resources/data-local.sql
`SELECT setval(pg_get_serial_sequence('table_name', 'id'), (SELECT MAX(id) FROM table_name));` needs to be called after each table's `INSERT` statement to resync the sequence. This has already been done for the tables that existed before this PR, so you only need to add it for property, payment, and property_ownership.

2024-12-13 10:07 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyRegistrationService.kt
> +@Scope(value = WebApplicationContext.SCOPE_REQUEST, proxyMode = ScopedProxyMode.TARGET_CLASS)
I managed to crib from the one service that was interacting with the session data didn't I...

2024-12-13 10:13 UTC, JasminConterioSW commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyRegistrationServiceTests.kt
> +    @InjectMocks
Yep, we're using it for some of the other service tests as well (like LocalAuthorityDataServiceTests)

2024-12-13 10:32 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/database/repository/PropertyOwnershipRepository.kt
> +    fun findByProperty_Id(id: Long): List<PropertyOwnership>
So just to confirm, for multiple landlords / joint ownership, we are expecting a property to have  (up to) 1 active ownership, and that ownership can have multiple landlords (at the moment, it just has one primary landlord, but there might be an "additional_landlords" field later)?

I think that does sound right, in which case your suggestion makes sense!

2024-12-13 10:50 UTC, JasminConterioSW commented on src/main/resources/db/migrations/V1_8_0__property_ownership_tables.sql
> +    ADD CONSTRAINT uc_propertyownership_property UNIQUE (property_id);
Yes, makes sense thank you!

2024-12-13 11:10 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/PropertyOwnership.kt
> +    @ManyToOne(optional = false)
Do they have to pay before property details are added to the database?
As there is a "draft" registration status I suspect not...

Assuming they don't have to pay before any details are saved, maybe we actually need to make the payment on PropertyOwnership optional (I don't know what we do if they haven't paid, presumably keep the RegistrationStatus as draft, maybe make the property / propertyownership inactive or something like that. Maybe not a question for right now)

2024-12-16 11:33 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/database/entity/Payment.kt
> +        private set
There should be, we'll remove the Payment table for now as we're not quite sure how we will want it to work!

2024-12-16 12:16 UTC, AEPR reviewed
Looking good! I've noticed a potential performance issue from repeated database calls. I'm not sure whether it's best to fix as part of this PR or merge and raise a new one to handle it? 

Happy to approve if we decide an approach to address this in another PR!

2024-12-16 12:16 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt
> +                if (addressData?.uprn != null && propertyRegistrationService.getIsAddressRegistered(addressData.uprn)) {
This function gets set to a `nextAction`, which means that it gets called repeatedly when the user is filling in the form (specificaly once when they submit this page, and twice when they get each subsequent page). That means that we're making a lot of duplicated database calls when we don't expect anything to change and that will probably have a negative impact on performance. 

I think we should probably only check this twice - once when they first select the address and once when we're about to save to the database (N.B. the database is actually enforcing this rule so even if we mess up our data is safe!).

I can think of two ways that we could do that - either we should cache the results of this check in the session so we don't keep hitting the database, OR we write a custom endpoint for `POST select-address` that does this check in the controller before calling `updateJourneyDataAndGetViewNameOrRedirect`.

2024-12-16 12:25 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt
> +                if (addressData?.uprn != null && propertyRegistrationService.getIsAddressRegistered(addressData.uprn)) {
Ooh I hadn't thought about the nextAction getting called on all the subsequent pages...

I think we can just cache it in the session though, I can add the private function back in and get it to check the cache for a result, then the database if it can't find a result in the cache.

2024-12-16 15:35 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/PropertyRegistrationJourney.kt
> +                if (addressData?.uprn != null && propertyRegistrationService.getIsAddressRegistered(addressData.uprn)) {
Took a little while but I think it's there...

It's caching the result for each uprn that it looks for (only the one that is selected, but if you keep going back and forth and select different properties it will store all of their results)

2024-12-16 15:57 UTC, isobel-softwire commented on src/main/resources/db/migrations/V1_8_0__property_ownership_tables.sql
> +    payment_id             BIGINT,
If we're leaving out the payment table, should this line be deleted?

2024-12-16 15:59 UTC, JasminConterioSW commented on src/main/resources/db/migrations/V1_8_0__property_ownership_tables.sql
> +    payment_id             BIGINT,
Good catch, yes it should

2024-12-16 16:36 UTC, AEPR approved these changes
3 really minor comments, but the actual caching looks sweet - I hadn't really thought about it but what you've done seems like a really nice system to make sure we catch someone repeatedly changing the address they're selecting!

2024-12-16 16:36 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/AddressRegisteredDataModel.kt
> +data class AddressRegisteredDataModel(
I don't think you're actually using this class anywhere.

2024-12-16 16:36 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/services/PropertyRegistrationService.kt
> +        return (databaseResult)
I don't think `databaseResult` needs to be in brackets here.

2024-12-16 16:36 UTC, AEPR commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/services/AddressDataServiceTests.kt
> +        assertFalse(addressDataService.getCachedAddressRegisteredResult(uprn) ?: true)
I'd split this up into 4 smaller tests here.

2024-12-16 16:45 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/AddressRegisteredDataModel.kt
> +data class AddressRegisteredDataModel(
Argh, no I'm not... I was in one iteration then realised I didn't need it!

2024-12-16 16:59 UTC, merged