Feat/prsd 495 data retrieval
communitiesuk/prsdb-webapp pull request #114
Opened 2024-12-18 13:55 UTC by JasminConterioSW

Adds in some helpers to retrieve data from the JourneyData for Property Registration.

These can be used to retrieve data to show on the Check Answers page, and also to get the data to save to the database.

2024-12-18 16:32 UTC, isobel-softwire requested changes
This is looking great so far! I left a few thoughts

2024-12-18 16:32 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/PropertyRegistrationJourneyDataHelper.kt
> +            }
I think this would be even easier to read if there was a `isManualAddressChosen()` method, like in the `LandlordJourneyDataHelper`

2024-12-18 16:32 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/PropertyRegistrationJourneyDataHelper.kt
> +        }
Do you think it would be worth adding a `getFieldEnumValue` to `JourneyDataService`?

2024-12-18 16:32 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/services/AddressDataService.kt
> +    }
This is definitely more convenient than repeating the method in each journey helper, but I don't think this method belongs here as it doesn't interact with address data stored in session. Maybe instead there should be a base `JourneyDataHelper` for common methods, which the specific helpers can delegate to?

2024-12-18 16:46 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/services/AddressDataService.kt
> +    }
The other methods aren't talking journeyData but they are still interacting with address-related data in the session, so I think this is ok?

2024-12-18 17:12 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/services/AddressDataService.kt
> +    }
I meant more for separation of concerns - the `AddressDataService` should only include methods that deal with cached addresses, but `getManualAddress` requires the service to know about the structure of the journey data.

2024-12-19 09:44 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/PropertyRegistrationJourneyDataHelper.kt
> +        }
It gets a little more complicated doing things with a generic enum type.

I think something like this will work though:

```
companion object {
        inline fun <reified E : Enum<E>> getFieldEnumValue(
            journeyDataService: JourneyDataService,
            journeyData: JourneyData,
            urlPathSegment: String,
            fieldName: String,
            subPageNumber: Int? = null,
        ): E? {
            val fieldAsString = journeyDataService.getFieldStringValue(journeyData, urlPathSegment, fieldName, subPageNumber) ?: return null
            return enumValueOf<E>(fieldAsString)
        }
    }
```

2024-12-19 10:08 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/helpers/PropertyRegistrationJourneyDataHelper.kt
> +        }
LGTM 😄

2024-12-19 10:52 UTC, JasminConterioSW commented
@isobel-softwire I think those changes should all be in :)

2024-12-19 10:54 UTC, isobel-softwire approved these changes
LGTM 👍

2024-12-19 11:00 UTC, merged