Feat/prsd 495 register property check answer page
communitiesuk/prsdb-webapp pull request #122
Opened 2024-12-20 16:41 UTC by AEPR

There's going to be a failing test or two in the Landlord Registration journey. These are caused by a genuine failure case because the landlords name cannot be read since they're null. PRSD-372 will fix this problem.

![image](https://github.com/user-attachments/assets/cb0b721c-d790-482d-bfd9-1caed7308bc3)

2025-01-06 12:55 UTC, isobel-softwire requested changes
The `JourneyDataBuilder` and `MessageKeyConverter` look great and will be very helpful for other journey stuff!  I've left some thoughts, mostly on refactoring.

2025-01-06 12:55 UTC, isobel-softwire commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/JourneyDataBuilder.kt
I think this should go in the `mockObjects` package

2025-01-06 12:55 UTC, isobel-softwire commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/JourneyDataBuilder.kt
> +                    ),
I think corresponding default address data should be set in `default()`, like in `withSelectedAddress()`, rather than setting it in `PropertyRegistrationCheckAnswersPageTest.setup()` (that seems to be where you're setting it currently?)

2025-01-06 12:55 UTC, isobel-softwire commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPageTest.kt
> +        val propertyDetails = model.asMap()["propertyDetails"] as List<*>
You could use `(model["propertyDetails"] as List<*>).filterIsInstance<FormSummaryViewModel>()` to give this method a `List<FormSummaryViewModel>` return type

2025-01-06 12:55 UTC, isobel-softwire commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPageTest.kt
Super minor, but this file should end in 'Tests' to fit with our other test files

2025-01-07 09:36 UTC, AEPR reviewed
Just the test improvements so far - I'll continue on to the comments on the main code now.

2025-01-07 09:36 UTC, AEPR commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/JourneyDataBuilder.kt
Yep, agree.

2025-01-07 09:36 UTC, AEPR commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/JourneyDataBuilder.kt
> +                    ),
Makes sense - I've decided to use `withSelectedAddress` in the `default` method to avoid repeating code, rather than setting the address data on the mock `AddressDataService` directly.

2025-01-07 09:36 UTC, AEPR commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPageTest.kt
> +        val propertyDetails = model.asMap()["propertyDetails"] as List<*>
I've done it over two lines to avoid needing to use the bracket wrap on the filter call, but yes that makes all of this a lot clearer and is a neat trick - I've definitely had a couple of times where I've been frustrated by a `List<*>`s where this would have helped!

2025-01-07 09:36 UTC, AEPR commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/models/dataModels/FormSummaryViewModelTest.kt
> +    @MethodSource("getConvertableValues")
Agree, that sounds nice but I wasn't quite sure how! I'll have a think after we've got Kiran's PR merged in.

2025-01-07 09:37 UTC, AEPR commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/JourneyDataBuilder.kt
> +    initialJourneyData: Map<String, Any?>?,
Done!

2025-01-07 09:49 UTC, isobel-softwire commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/JourneyDataBuilder.kt
> +                    ),
Sounds good 😄

2025-01-07 09:50 UTC, AEPR commented on src/main/resources/templates/fragments/summaryList.html
> +        </dd>
That's good to know, but they're not currently producing quite the same html - if there's only one item it goes directly in the `<dd>` element whereas the list of items results in a bunch of `<div>`s. Combining these two blocks would result in every summary item with only one item having a single `<div>` with the content which is a bit messier imo (and I don't know if it could have accessibility impacts). The advantage would be a simpler fragment here and removing the `isListSummaryItem` function on the `ViewModel`.

I'm not sure which I prefer - or if there are any more meaningful unfortunate implications of having a bunch of lonely `div`s.

2025-01-07 10:03 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPage.kt
> +        val licenceNumber = getLicenceNumberOfType(licensingType, journeyData)
Moved it too and copied the code from there - one of us (or @JasminConterioSW ) will need to manage the merege conflict

2025-01-07 10:08 UTC, isobel-softwire commented on src/main/resources/templates/fragments/summaryList.html
> +        </dd>
The [GDS Summary List](https://design-system.service.gov.uk/components/summary-list/) uses `<p>`s for lists of items instead of `<div>`s. I feel like a single `<p>` in a `<dd>` is clean enough - what do you think?

2025-01-07 10:08 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPage.kt
> +        DataHelper.getAddress(journeyDataService, journeyData, addressDataService)?.singleLineAddress
Yeah, this does make sense - we should be asserting that all of these are present unless we're explicitly sure that they shouldn't be! (Or explictly uncertain e.g. for the custom property type)

2025-01-07 10:22 UTC, AEPR commented on src/main/resources/templates/fragments/summaryList.html
> +        </dd>
For sure should be using `<p>`s instead of `<div>`s either way, I had thought that when writing the comment above but didn't want to confuse the issue at hand. 😅

2025-01-07 10:24 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPage.kt
> +        val propertyType = DataHelper.getPropertyType(journeyDataService, journeyData)!!
Yeah, we should probably make this all consistent and clear with an explicit exception. I think we should package that up with the other journey data improvements though, and make sure we do it ahead of future form journeys.

2025-01-07 10:29 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPage.kt
> +                RegisterPropertyStepId.LookupAddress.urlPathSegment,
I think this is better because if you're changing the address you might be changing it to a looked up address. BUT it's not my call - IMO we should check with the design team and follow that. I don't have explicitly different designs for checking manual vs selected addresses so I'll raise it on Slack.

2025-01-07 11:08 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPage.kt
> +            DataHelper.getOwnershipType(journeyDataService, journeyData),
Fixed

2025-01-07 11:29 UTC, AEPR commented
Addressed everything except the two unresolved conversations - hopefully both will be bottomed out today.

2025-01-07 11:37 UTC, isobel-softwire approved these changes

2025-01-07 14:18 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/PropertyRegistrationCheckAnswersPage.kt
> +                RegisterPropertyStepId.LookupAddress.urlPathSegment,
Checked with Nicola and she's confirmed that the landlord registration check page is correct, so I've updated this to match. It's meant that the previous commonisation of this section (and the `listOfNotNull`) is not longer useful so I've split it out into two sub functions (one for selected and one for manual).

2025-01-07 16:12 UTC, merged