Feat/prsd 491 manual address entry
communitiesuk/prsdb-webapp pull request #92
Opened 2024-12-09 15:03 UTC by JasminConterioSW

- Add a manual address page (similar to the landlord registration journey)
- Add a "Select local authority" page 
- Added tests

![image](https://github.com/user-attachments/assets/afe28ecd-7778-4e46-8e3c-11bc7eb9dcf6)

UPDATED SCREENSHOT
![image](https://github.com/user-attachments/assets/e9e6e2b0-2581-47ea-b0bf-f7153565486b)

2024-12-09 15:05 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/LocalAuthorityConstants.kt
> +        val nameInQuotationMarks = line.split("\"")
There is one LA which has commas in it's name (Bournemouth, Christchurch and Poole Council), in the CSV file the name is surrounded by "".
This gets that name before splitting up fields by comma!

2024-12-09 15:06 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/PlaceNameConstants.kt
> +        val nameInQuotationMarks = line.split("\"")
Again there are a couple of countries where the full name wasn't showing because it had a comma in the middle (e.g. "Pitcairn, Henderson, Ducie and Oeno Islands")

2024-12-09 15:54 UTC, isobel-softwire approved these changes
Left a few minor comments but LGTM 👍

2024-12-09 15:54 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/LocalAuthorityConstants.kt
Local authorities aren't capitalized on the check answers page in the Figma - they should probably be formatted here

2024-12-09 15:54 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/PlaceNameConstants.kt
> +        val nameInQuotationMarks = line.split("\"")
Nice spot 😄

2024-12-09 15:54 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/steps/RegisterPropertyStepId.kt
> +    SelectLocalAuthority("select-local-authority"),
This can just be `LocalAuthority` and `"local-authority"` if there's no other page that deals with local authorities

2024-12-09 15:54 UTC, isobel-softwire commented on src/main/resources/messages.properties
>  forms.manualAddress.fieldSetHeading=What is your address?
This can be changed to `forms.manualAddress.landlordRegistration.fieldSetHeading` to fix the new line

2024-12-09 16:24 UTC, AEPR requested changes
Looking good - just a couple of minor thoughts/queries!

2024-12-09 16:24 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/LocalAuthorityConstants.kt
> +        val nameInQuotationMarks = line.split("\"")
🤦Of course there is. There's something upsetting about the fact that it's only one exception.

I think that this is non-obvious enough that it's probably worth including a comment in this class to the effect of "commas in local authority names are escaped by containing the name in quotation marks" or similar.

2024-12-09 16:24 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/LocalAuthorityConstants.kt
> +        localAuthorities.add(LocalAuthorityDataModel(uprn, displayName))
I assume that there's been no discussion of treating non-english councils differently? I heard it mentioned on Thursday, but I expect that it's a "maybe someday" feature. Might be worth flagging in standup at some point to make sure there's something in the backlog, on the roadmap or whereever it should belong!

2024-12-09 16:24 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/LocalAuthorityConstants.kt
> +package uk.gov.communities.prsdb.webapp.constants
I'm made very vaguely uncomfortable that this and placenames are in files called constants when technically they're not `const`s, but being read from a file on startup, but I'm not sure what else we'd call this and they're never changing at run time so I don't think there's any real problem.

2024-12-09 16:24 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/SelectViewModel.kt
>      val labelMsgKey: String? = null,
I don't think `labelMsgKey` is ever actually used, which (if I'm right) would mean you can get rid of it and wouldn't need to have the nested ternary statement in the select form component. 

It also makes sense that when you're using a select there are likely to be enough options that they don't all get their own internationalisable labels. What do you think?

2024-12-09 16:34 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/LocalAuthorityConstants.kt
I think we should probably just trust the formatting in the CSV rather than a DIY solution until we have reason to do that and we can make it a separate ticket. It feels like it will probably be a lot of work that would be better served by just storing the nicely formatted names in the first place!

2024-12-09 16:34 UTC, AEPR commented on src/main/resources/templates/fragments/forms/select.html
> +                    : option.value)}">
I think this is a little unclear to read as is - ideally there'd be a way to not do a nested ternary but failing that maybe 
```
${option.labelMsgKey != null 
    ? #messages.msg(option.labelMsgKey)
    : (option.label != null ? option.label : option.value)}
```
?

2024-12-10 09:05 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/LocalAuthorityConstants.kt
Yeah that makes sense - its annoying that the CSV isn't formatted nicely

2024-12-10 09:10 UTC, JasminConterioSW commented on src/main/resources/data/local_authorities/addressbase-local-custodian-codes.csv
> +AUTH_CODE,ACCOUNT_NAME,ACCOUNT_TYPE_NAME,ADDRESS_SUBMITTER_FLAG,STREET_SUBMITTER_FLAG,SUBMITTER_FLAG
Sorry, I should have left a comment telling you not to!

2024-12-10 09:12 UTC, JasminConterioSW commented on src/main/resources/messages.properties
> +forms.selectLocalAuthority.paragraph.one.linkText=find your local authority by searching using the property postcode (opens in new tab).
Oops you're quite right, I missed that bit!

2024-12-10 09:50 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/models/viewModels/SelectViewModel.kt
>      val labelMsgKey: String? = null,
Hmm I think you're right, when then are only a few options we're more likely to be using radio buttons...
At the moment, this is used in the CountryOfResidence form page but only the value is used.

2024-12-10 09:55 UTC, JasminConterioSW commented on src/main/resources/templates/fragments/forms/select.html
> +                    : option.value)}">
We don't need this if we are taking out the labelMsgKey (if it turns out we do need it, we can always add it back in!)

2024-12-10 11:15 UTC, AEPR commented on src/main/resources/templates/forms/selectLocalAuthorityForm.html
> +</div>
Sorry - I think I've given a bit of a bum steer on this. I agree with my original point but didn't understand how the `questionPage` fragment worked (it creates an `html` tag and a `form` tag). What I wanted was for the structure of this to approximately match the eventual rendered page i.e.

```
<html...
    <form...
        <fieldset....
        <button....
```

I also think we should avoid using `th:blocks` if they're going to be replaced (but use them when we need to group elements for Thymeleaf but not have a real element!). 

So, I think `#fieldset-content` should be a `fieldset` and the `select` fragment should be a `select`. `#form-content` shouldn't be a real div when thymeleaf has processed so either it should be a `form` with `th:remove="tag"` or it should be a `th:block` (as you had intially).

2024-12-10 11:48 UTC, JasminConterioSW commented on src/main/resources/templates/forms/selectLocalAuthorityForm.html
> +</div>
Ah ok, I think this is right now?

2024-12-10 12:25 UTC, AEPR commented on src/main/resources/templates/forms/selectLocalAuthorityForm.html
> +</div>
Yeah - so do I. I'm probably being a little bit pernickety about this to be honest (and I know you're following the convention from another file). I'll bring it up at Catch Up tomorrow anyway as it would probably good if we standardised on how we're doing this more!

2024-12-10 12:28 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/LocalAuthorityConstants.kt
> +        localAuthorities.add(LocalAuthorityDataModel(uprn, displayName))
I've just realised that I've actually also got an outstanding missing external link on another page. I think that both of these issues should probably be raised outside of this PR which otherwise all looks good to me!

2024-12-10 12:28 UTC, AEPR approved these changes
Looks good!

2024-12-10 13:39 UTC, JasminConterioSW commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/constants/LocalAuthorityConstants.kt
> +        localAuthorities.add(LocalAuthorityDataModel(uprn, displayName))
Moved this discussion to slack :)
https://softwire.slack.com/archives/C07P6L76A1L/p1733837893612729

2024-12-10 13:40 UTC, merged