Feat/prsd 372 landlord registration check answers
communitiesuk/prsdb-webapp pull request #93
Opened 2024-12-09 16:03 UTC by Kiran-R-K

- created the check answers journey step
- created the `LandlordRegistrationCheckAnswersPage` to to populate the model that should be returned for this page
- ensured the page renders the correct data and links according to users input
- ensured that data is persisted through each journey flow (so if a user changes from being a UK resident and back again the data they input from that flow prepopulates when they return to the pages)
- updated existing tests and created new ones

Notes:
- There are not yet integration tests to check the page when a user has had their ID verified by one login - they were proving tricky and I felt it was better to get the PR in while I worked on them.
- Some references to the check answers page were using `CheckAnswersPage` in their name and some were using `SummaryPage` I have changed them all to `CheckAnswersPage` for consistency.

2024-12-09 17:24 UTC, isobel-softwire reviewed
Left some comments, mostly about testing, but this looks great 👍

2024-12-09 17:24 UTC, isobel-softwire commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/LandlordRegistrationJourneyTests.kt
> +            }
I think a `SummaryList` page object component should be created and instantiated in `SummaryPageLandlordRegistration` instead of checking each row title and value independently. (It should be quite similar to `Table`, I think?)

2024-12-09 17:24 UTC, isobel-softwire commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordRegistrationJourneyPages/CheckAnswersPageLandlordRegistration.kt
> +    fun getAllChangeLinks() = BaseComponent.getAllLinks(page, "Change")
I don't think there should be methods that return multiple locators, as a test for locator 2 would fail if locator 1 can't be found. Instead, links should specified by more specific criteria than text here.

2024-12-09 17:24 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt
> +            .joinToString(", ")
I've now merged in `AddressDataModel.manualAddressDataToSingleLineAddress` which does this

2024-12-09 17:24 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt
> +    }
Feel like we'll need this method and methods like it (i.e. methods that combine multiple form data fields) across multiple pages. Not sure what file they should go in though - @Travis-Softwire?

2024-12-09 17:24 UTC, isobel-softwire commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/components/BaseComponent.kt
As mentioned in the comments on `CheckAnswersPageLandlordRegistration`, I don't think we should be using these new methods

2024-12-10 09:41 UTC, AEPR reviewed
Reviewed test files, nothing to add that @isobel-softwire hasn't already said!

2024-12-10 10:52 UTC, Kiran-R-K commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt
> +            FormSummaryDataModel(
I don't think so. This is being used for both check answer pages and for the confirm identity page so I don't think it's a clear cut name change. It's also the model that is being used to populate the summary lists, so I left it as it is but I'm also happy to be suggested otherwise?

2024-12-10 10:53 UTC, Kiran-R-K commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt
> +        return super.populateModelAndGetTemplateName(validator, model, pageData, prevStepUrl, journeyData)
I'm not sure I follow, how come?

2024-12-10 11:05 UTC, Kiran-R-K commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/integration/pageObjects/pages/landlordRegistrationJourneyPages/CheckAnswersPageLandlordRegistration.kt
> +    fun getAllChangeLinks() = BaseComponent.getAllLinks(page, "Change")
This is (now*) being used to get all change links and the test will count how many there are on a page to verify the correct number have been rendered

* I don't think it was at the time of your comment

2024-12-10 11:28 UTC, AEPR commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt
> +            FormSummaryDataModel(
That makes sense to me, happy to leave it as is as long as we've thought about it!

2024-12-10 13:14 UTC, Kiran-R-K commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt
> +            .joinToString(", ")
So interestingly `AddressDataModel.manualAddressDataToSingleLineAddress` is serializing the address in a slightly different order:
`addressLineOne, addressLineTwo, townOrCity, postcode, county`
and I had been displaying the address in this order:
`addressLineOne, addressLineTwo, townOrCity, county, postcode`
I had been working under the assumption that we would follow the same order as the manual address input page and I'm inclined to keep it that way for the view.
 Would updating the the AddressDataModel to format the address this way `addressLineOne, addressLineTwo, townOrCity, county, postcode` be a problem for the way it's being used elsewhere?

2024-12-10 16:08 UTC, Kiran-R-K commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt
> +    }
I've created a `DateFormatterService` I'm not sure if that's where it should go, but it's a start we can move later if we want

2024-12-11 09:59 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt
> +            .joinToString(", ")
Oh, that actually makes sense - I'll change this in my current ticket as it links.

2024-12-11 18:47 UTC, Kiran-R-K commented
Things left to do on this ticket are:
The pipeline is failing on a test that's passing locally - figure out why and fix it
Action this comment: https://github.com/communitiesuk/prsdb-webapp/pull/93#discussion_r1876297208
Action this comment: https://github.com/communitiesuk/prsdb-webapp/pull/93#discussion_r1876353775
Tis discussion is ongoing, speak to Travis about it: https://github.com/communitiesuk/prsdb-webapp/pull/93#discussion_r1876367323

2024-12-13 09:58 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt
> +            .joinToString(", ")
It's not merged in yet, but in PR #103, there's a `JourneyDataService.getManualAddress` method that would be helpful here. It creates an `AddressDataModel` (which has a `toString` method) from the manual address fields in the journey data.

2024-12-18 10:21 UTC, Kiran-R-K commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordRegistrationJourney.kt
> +        }
This was removed/moved elsewhere on main but I'm calling it from the `LandlordRegistrationCheckAnswersPage` so I kept it in when rebasing - this might need removing again and having the `LandlordRegistrationCheckAnswersPage` call the method from elsewhere

2024-12-18 10:23 UTC, Kiran-R-K commented on src/main/resources/messages.properties
> +commonText.no=No
I'm not sure about the names of these message keys

2024-12-18 10:37 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/journeys/LandlordRegistrationJourney.kt
> +        }
I moved this method to the `LandlordJourneyDataHelper` (it's called `isIdentityVerified` there)

2025-01-06 13:17 UTC, isobel-softwire commented on src/main/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPage.kt
> +                if (isIdentityVerified) null else "/${BASE_CHANGE_URL}/${LandlordRegistrationStepId.Name.urlPathSegment}",
`urlPathSegment` works - thanks 😄

2025-01-07 16:19 UTC, isobel-softwire commented
> @isobel-softwire - I've merged my PR into main so this can be rebased/mave main merged into it and you can e.g. return booleans directly in the `CheckAnswersPage` and resolve conflicts. It could make sense to pair on it but I don't mind either way - up to you.

Thanks! I'll give it a lookover and ping you if I need help

2025-01-07 16:40 UTC, isobel-softwire commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/helpers/LandlordJourneyDataHelperTests.kt
> +    @CsvSource("true,", "false,$COUNTRY_OF_RESIDENCE")
That makes sense - I'll change them in this file

2025-01-08 14:53 UTC, AEPR requested changes
Couple of testing points but otherwise all looking good.

2025-01-08 14:53 UTC, AEPR commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPageTests.kt
> +        val journeyData = journeyDataBuilder.build()
I don't think this test should rely on the default journey data. The purpose of the default journey is so that there are no errors when running the tests. The actual test cases should be set up from the test in question (or the tests set up) each time even if it's duplicating what's already there. That way if someone changes the default `JourneyDataBuilder` for some reason it should affect these tests.

It also makes the tests easier to understand by just looking at the test - e.g. you don't need to know that the default journey data has an unverified identity for this test to work. (Since "DEFAULT_NAME" doens't communicate that it's unverified).

2025-01-08 15:23 UTC, isobel-softwire commented on src/test/kotlin/uk/gov/communities/prsdb/webapp/forms/pages/LandlordRegistrationCheckAnswersPageTests.kt
> +        val journeyData = journeyDataBuilder.build()
That makes sense - I've made these changes and the one from your other comment 👍

2025-01-08 15:35 UTC, AEPR approved these changes
Looks great!

2025-01-08 15:35 UTC, merged